name = "lacrosse-robotics-site"
main = "worker/index.js"
compatibility_date = "2026-02-15"
account_id = "cfb5806341f9c812f37277262ce16c3a"

[[d1_databases]]
binding = "DB"
database_name = "lacrosse-robotics-events"
database_id = "12ff1932-e65c-43d7-87cd-9e153650715b"
