name = "lacrosse-robotics-api"
main = "worker/index.js"
compatibility_date = "2024-01-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "lacrosse-robotics-events"
database_id = "12ff1932-e65c-43d7-87cd-9e153650715b" # Will be filled after creating the database

[vars]
ALLOWED_ORIGINS = "https://lacrosserobotics.com,http://localhost:8000"
